# Generated by Django 3.0.10 on 2022-08-01 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0002_genre_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='description',
        ),
    ]
