# Generated by Django 3.0.10 on 2022-08-01 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0003_remove_genre_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Genre',
        ),
    ]
