# Generated by Django 3.0.10 on 2022-08-02 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0007_auto_20220802_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='birth',
            field=models.DateField(default=None, null=True),
        ),
    ]
