# Generated by Django 3.0.10 on 2022-08-02 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0008_auto_20220802_1855'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actor',
            name='birth',
        ),
    ]
