# Generated by Django 3.0.10 on 2022-08-09 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0012_movie_rating'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Movie',
        ),
    ]
